### ISSUE TITLE
Release WSK 0.4.1

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#364]
Remaining items:
- [x] Fix for changed files in the styles:css task #308 
- [x] Improve overview section of readme #362 
- [x] Decide on including JSCS configuration in #363 
- [x] Add mention of web-starter-kit-extras to README. #365
- [x] Add section on WSK and CSS libraries #367 
- [x] Write the release notes
- [x] Get the CLA bot setup #247 

Purposefully keeping the list of todos here small as it's been ~ month since we last released.
