### ISSUE TITLE
0.6.0 Release Checklist

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#415]
## P1
- [ ] Material Design Styleguide + Layout (CSS Only)
- [ ] Material Design (Lite) Components (Dev Preview)
- [ ] WSK Lite
- [ ] More Docs (Recipes / Braindumps / Browser Sync info)
- [ ] Bring in the new Roboto Draft
## P2
- [ ] Developer Survey
- [ ] Explore ability to change 'app' and 'dist' directories in one place
- [ ] Explore JS Configuration & Gulp file Simplification
- [ ] Automate update homepage for releases
## P3
- [ ] Stretch Goal - Layouts - Need an owner
## P4
- [ ] Explore single installation package for all dependencies - Replicate node install
